import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Grid Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-poppins antialiased mx-auto p-4 sm:max-w-xl md:max-2xl lg:max-3xl xl:max-w-6xl flex-col">
        
        {children}
      </body>
    </html>
  );
}
